name: test terabox proxy
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Test sharelist
        run: |
          curl -s -X POST 'https://github-actions-test...' 
        env:
          NDUS: ${{ secrets.NDUS }}
      
      - uses: actions/upload-artifact@v4
        with:
          name: result
          path: result.json
